В цьому домашньому завданні продовжуємо працювати з набором даних supermarket_sales.csv.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну df типу pandas.DataFrame.

In [3]:
import numpy as np
import pandas as pd

In [4]:
import os
os.listdir('../data')

['.ipynb_checkpoints',
 'sample_submission.csv',
 'supermarket_sales.csv',
 'train.csv']

In [5]:
data_path = '../data/supermarket_sales.csv'
df = pd.read_csv(data_path)

1. Відсортуйте дані за спаданням ціни товара ('Unit price') і виведіть 5 перших рядочків на екран.

In [8]:
df.sort_values(by='Unit price', ascending = False).head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
983,148-41-7930,C,Naypyitaw,Normal,Male,Health and beauty,99.96,7,34.986,734.706,1/23/2019,10:33,Cash,699.72,4.761905,34.986,6.1
122,219-22-9386,B,Mandalay,Member,Male,Sports and travel,99.96,9,44.982,944.622,3/9/2019,17:26,Credit card,899.64,4.761905,44.982,4.2
930,641-62-7288,B,Mandalay,Normal,Male,Home and lifestyle,99.92,6,29.976,629.496,3/24/2019,13:33,Ewallet,599.52,4.761905,29.976,7.1
494,437-53-3084,B,Mandalay,Normal,Male,Fashion accessories,99.89,2,9.989,209.769,2/26/2019,11:48,Ewallet,199.78,4.761905,9.989,7.1
283,667-92-0055,A,Yangon,Member,Male,Health and beauty,99.83,6,29.949,628.929,3/4/2019,15:02,Ewallet,598.98,4.761905,29.949,8.5

2. Знайдіть інвойс (рядок в даних) в категорії товарів Electronic accessories, в якому був куплений товар з найбільшою кількістю і найбільшою ціною. Виведіть цей рядок даних на екран.

In [46]:
df.query("`Product line` == 'Electronic accessories'").sort_values(by=['Unit price', 'Quantity'], ascending=[False, False]).head(1)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Rating Category
209,817-69-8206,B,Mandalay,Normal,Female,Electronic accessories,99.73,9,44.8785,942.4485,3/2/2019,19:42,Credit card,897.57,4.761905,44.8785,6.5,Medium

3.1 Створіть нову колонку в даних Rating Category, яка визначає категорію рейтингу (Rating): високий, середній чи низький за наступним правилом:

якщо рейтинг вищий або рівний 8 - то він високий (High)
якщо рейтинг від 6 (включно) до 8 (не включно) - то він середній (Medium)
інакше - низький (Low).

In [47]:
def Rating(rate):
    if rate >= 8:
        return "High"
    elif 6 <= rate < 8:
        return "Medium"
    else:
        return "Low"

In [48]:
df['Rating Category'] = df['Rating'].apply(Rating)

In [52]:
df['Rating Category'].head()

0      High
1      High
2    Medium
3      High
4       Low
Name: Rating Category, dtype: object

In [53]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Rating Category
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1,High
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6,High
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4,Medium
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4,High
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3,Low

3.2. Виведіть, який відсоток даних становить кожне зі значень категорій рейтингу.

In [56]:
rating_cat_counts = df['Rating Category'].value_counts() 
df['Rating Category'].value_counts(normalize=True)*100

Rating Category
Medium    35.6
High      32.9
Low       31.5
Name: proportion, dtype: float64

4.1 Запустіть код нижче аби створити змінну time. Ця змінна містить час в форматі "година:хвилина". Напишіть функцію get_hour, яка буде зі змінної формату як time дістати лише години і конвертувати їх у тип int.

Запустіть написану функцію на змінній time та перевірте правильність роботи функції.

In [57]:
time = '11:28'

In [59]:
def get_hour(h):
    return int(h[:2])

In [61]:
result = get_hour(time)
print(result)
type(result)

11

int

4.2 За допомогою функції get_hour і метода DataFrame.apply() створіть нову колонку Hour в нашому наборі даних, яка буде містити години здійснення покупки, обчислені на основі часу здійснення покупки Time.

In [67]:
df['Hour'] = df.Time.apply(get_hour)
df[['Time', 'Hour']].head()

    Time  Hour
0  13:08    13
1  10:29    10
2  13:23    13
3  20:33    20
4  10:37    10

4.3 Виведіть кількість значень за кожною годиною покупки і дайте відповідь "О яких годинах найбільше здійснюють покупок покупці і чому на Ваш погляд саме о цих годинах? Чи це слогічно, що найбільше покупок саме в ці години?".

In [71]:
df['Hour'].value_counts()

Hour
19    113
13    103
15    102
10    101
18     93
11     90
12     89
14     83
16     77
20     75
17     74
Name: count, dtype: int64

Найбільше покупок здійснюється о 19-й годині, потім о 13,15 і 10-й.
О 19-й покупці після роботи заходять у магазин по дорозі додому, щоб скупитись.
О 13-й люди мають  обідню перерву і тому можуть поєднувати обід і покупки в супермаркеті.
О 15-й - це може бути coffee break у працівників і завершення навчання у школах\університетах, або пенсіонери, фрілансери, люди не з офісним графіком роблять покупки у менш завантажені години.
О 10-й - покупці заходять перед роботою, щоб скупитись або перший coffee break після початку робочого дня. Ще одна гіпотеза, що пенсіонери, фрілансери, люди не з офісним графіком роблять покупки у менш завантажені години.

5. Виведіть середнє значення чеку (Total) для покупок в містах, наявних в даних, за допомогою функції groupby.

In [73]:
city_group = df.groupby('City')
print(city_group)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000001FFF3995E50>

In [79]:
average_total = city_group['Total'].mean()
print(average_total)

City
Mandalay     319.872506
Naypyitaw    337.099715
Yangon       312.354031
Name: Total, dtype: float64

6. Виведіть кількість покупок, середнє, мінімальне та максимальне значення для загальної суми чеку (Total) в містах, наявних в даних, за допомогою функції groupby. Зробіть висновки з цих показників та дайте рекомендації для мережі супермаркетів.

In [83]:
total_calculation = city_group['Total'].agg(['count','mean', 'min', 'max'])
print(total_calculation)

           count        mean      min      max
City
Mandalay     332  319.872506  18.6375  1022.49
Naypyitaw    328  337.099715  10.6785  1042.65
Yangon       340  312.354031  12.6945  1039.29

З огляду на дані, кількість покупок за містами розподілена приблизно рівномірно.
Середній чек у Naypyitaw є найвищим (337,10), тоді як у Yangon — найнижчим (312,35). Для цього міста я б рекомендувала проаналізувати крос-продажі, щоб підняти середній чек.
Мінімальна сума чека в Naypyitaw найнижча (10,68), і тому варто проаналізувати товарний ряд, щоб просувати дорожчі товари. Загалом, це ж саме можна застосувати і для Yangon.

7. Ми внесли деякі зміни в наш набір даних, тож, давайте запишемо результат у файл. Запишіть оновлену версію даних у файл supermarket_sales_enriched.csv. Зверніть увагу, аби не записати нічого зайвого, наприклад, індекси рядків нам в файлі не потрібні, оскільки вони стандартні.

In [84]:
df.to_csv('hw_10_3_advanced_data_processing_methods', index=False)

In [85]:
pd.read_csv('hw_10_3_advanced_data_processing_methods', nrows=5)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Rating Category,Hour
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1,High,13
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6,High,10
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4,Medium,13
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4,High,20
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3,Low,10